export { default as DefaultRender } from './DefaultRender.vue'
export { default as DockRender } from './DockRender.vue'
export { default as MenuBarRender } from './MenuBarRender.vue'
export { default as ShortcutBarRender } from './ShortcutBarRender.vue'
export { default as StatusBarRender } from './StatusBarRender.vue'
export { default as TitleBarRender } from './TitleBarRender.vue'
export { default as ToolBarRender } from './ToolBarRender.vue'
